### PR TITLE
Minor Fixes Alani and Neon

### PR DESCRIPTION
**Pull request by Nacurutu**
Minor Fixes Alani and Neon

### CODE REVIEW

**Comment by Gerschel** [comment]
Can you update matrix. It's the same as alani, just the base colors in the header were different.

**Comment by Nacurutu** [comment]
Done... if you want, from now on, every time I update Alani and Neon, I also can update Matrix. :)

**Comment by Gerschel** [comment]
I feel like, we should make a script that will allow you to make one file, then it swaps out the difference. Kind of like using the save feature changes just the header. That's how the matrix.css was made.

**Comment by Nacurutu** [comment]
> I feel like, we should make a script that will allow you to make one file, then it swaps out the difference. Kind of like using the save feature changes just the header. That's how the matrix.css was made.

Yep, that's a great idea to avoid broken theme files if the Authors don't update their files, and, if someone wants to use a different theme, they can just rename it as user.css and paste it into the root folder. 

Also, it gives me a relief just having to update one file, like a MasterDarkTheme, the parameters can be updated directly to that master file and we don going to need to have a lot of CSS files. just parameter saves. 

Remember to keep the ability to add new parameters to the master file, I think the read/write process you have right know works. with the breaker on the master file. 

in resume, we can have a MasterCSS

and then,.. a drop-down menu with the names:

- Alani
- Neon
- Matrix
- etc

And also, let the user create their own custom parameters and add them to this list

- Alani
- Neon
- Matrix
- Usercustom1
- Usercustom2
- etc

Also, I think we should remove (for now) the ability to change the logo, favicon, background, and animations, and just have the parameters, sliders, save parameters, and the list with the names.

(The logo should stay, but a fixed one, the one that is working now and used on the gallery and primary buttons, the same file, the gray one because it is compatible with all background colors we use due to the transparency it has).

Then, after you manage how to migrate the tab to settings, we can figure out how to bring back the options.

I think we should focus on that. My humble opinion.  what do you think?

Let's make it simpler for now.

**Pull request merged**
